sudo: false

language: python

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install --upgrade pip
  - pip install flake8

script:
  - flake8 --max-complexity 15 whatlogger/logger/what.py
  - python setup.py bdist_egg
